### ISSUE TITLE
Errors in exporting to Fiji

### ISSUE THREAD

**Issue by andrewsilberfeld** [BIOP/ijp-imagetoatlas#118]
ABBA isn't exporting several of the items to Fiji: I can't export regions to file or to ROI manager, nor can I export atlas coordinates or the actual atlas images to fiji. I see the error below for the atlas coordinates export function. Exporting regions to file / ROI manager runs but no output is observed. Am I doing something wrong?

<img width="956" alt="export error" src="https://user-images.githubusercontent.com/62805456/144382360-f0bb54cd-21e8-45a8-8be0-73b0af05b717.png">

**Comment by NicoKiaru** [comment]
Yes, that's a bug which occurs when all the regions are fully in the right hemispheres or in the left hemisphere. This is fixed in a newer version which I plan to release in about two weeks if everything goes right

**Comment by andrewsilberfeld** [comment]
Okay thank you!

**Comment by andrewsilberfeld** [comment]
It looks like all the export atlas coordinates and export images of slice or atlas are working now, however the regions export to fille or to ROI manager still doesn't work.

**Comment by andrewsilberfeld** [comment]
Sorry to bother you again! It looks like all the export atlas coordinates and export images of slice or atlas are working now, however the bug still effects exporting regions to file or to ROI manager.

**Comment by NicoKiaru** [comment]
Thanks for the report. FYI I won't have time to look at it before January

**Comment by andrewsilberfeld** [comment]
No worries thanks!

**Comment by NicoKiaru** [comment]
In the new version that I need (workshop in preparation) to release next Tuesday, it seems the export to ROI manager bug is gone. I removed the export to File option, because I thought it was not needed. But do you need it ? I can restore it

**Comment by andrewsilberfeld** [comment]
that's great! Actually please keep that option, it is helpful. It will be useful for saving many ROIsets en masse to be looped later in Fiji macro. Without it, I will have to save each one manually after it outputs.

**Comment by NicoKiaru** [comment]
Ok, this bug should be fixed now, and I restored the export to file option. @andrewsilberfeld please reopen if I forgot something.
